"""
Django settings for settings project.

Generated by "django-admin startproject" using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from urllib.parse import quote

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: don"t run with debug turned on in production!
DEBUG: bool = True

LOCAL_APPS: list = [
    "dashboard",
]

DJANGO_APPS: list = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
]

THIRD_PARTY_APPS: list = [
    "social_django",
    "psqlextra",
    "rest_framework",
]

INSTALLED_APPS: list = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE: list = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF: str = "settings.urls"

AUTHENTICATION_BACKENDS: list = [
    "social_core.backends.open_id_connect.OpenIdConnectAuth",
    "django.contrib.auth.backends.ModelBackend",
]

TEMPLATES: list = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "dashboard.utils.contexts_processors.django_settings"
            ],
        },
    },
]

WSGI_APPLICATION: str = "settings.wsgi.application"
ASGI_APPLICATION = "settings.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES: dict = {
    "default": {
        "ENGINE": "psqlextra.backend",
        "NAME": os.getenv("POSTGRES_DB", "pacer-dashboard"),
        "USER": os.getenv("POSTGRES_USER", "pacer-dashboard"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "<PASSWORD>"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}

PSQLEXTRA_PARTITIONING_MANAGER: str = "settings.pg_partition_manager.manager"

AUTH_PASSWORD_VALIDATORS: list = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


FIXTURE_DIRS: set = {
    os.path.join(BASE_DIR, "dashboard/tests/fixtures/"),
}

LANGUAGE_CODE: str = "en-us"
TIME_ZONE: str = "Europe/Madrid"
USE_I18N: bool = True
USE_TZ: bool = True

STATIC_URL: str = "/static/"
STATIC_ROOT: str = "./static/"
DEFAULT_AUTO_FIELD: str = "django.db.models.BigAutoField"

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

DISABLED_AUTH: bool = bool(os.getenv("DISABLED_AUTH", False))
SOCIAL_AUTH_JSONFIELD_ENABLED = True
SOCIAL_AUTH_OIDC_OIDC_ENDPOINT: str = os.getenv("SSO_SERVER_URL", "")
SOCIAL_AUTH_OIDC_KEY: str = os.getenv("SSO_CLIENT_ID", "")
SOCIAL_AUTH_OIDC_SECRET: str = os.getenv("SSO_CLIENT_SECRET", "")
SSO_LOGOUT_REDIRECT_URL = f"{SOCIAL_AUTH_OIDC_OIDC_ENDPOINT}/protocol/openid-connect/logout?client_id={SOCIAL_AUTH_OIDC_KEY}&post_logout_redirect_uri={{}}"

RABBITMQ_BROKER_SETTINGS: dict = {
    "protocol": os.getenv("RMQ_PROTOCOL", "amqp"),
    "host": os.getenv("RMQ_HOST", None),
    "port": os.getenv("RMQ_PORT", "5672"),
    "username": quote(os.getenv("RMQ_USERNAME", "pacer-dashboard")),
    "password": quote(os.getenv("RMQ_PASSWORD", "<PASSWORD>")),
    "vhost": os.getenv("RMQ_VHOST", "/")
}

ICAT_AUTH: dict = {
    "url": os.getenv("ICAT_SERVER_URL", ""),
    "username": os.getenv("ICAT_USERNAME", ""),
    "password": os.getenv("ICAT_PASSWORD", ""),
    "auth_plugin": os.getenv("ICAT_AUTH_PLUGIN", "db"),
}

PANOSC_AUTH: dict = {
    "url": os.getenv("PANOSC_API_URL", ""),
    "username": os.getenv("PANOSC_API_USERNAME", ""),
    "password": os.getenv("PANOSC_API_PASSWORD", ""),
}

INVESTIGATION_CHECK_MAX_RETRIES: int = 30
PACER_INV_OPERATION_MINT: str = "mint-proposal"
PACER_INV_OPERATION_PANOSC_ITEM: str = "create-panosc-item"

PACER_RMQ_HOST: str = os.getenv("RMQ_HOST", "")
PACER_RMQ_PORT: int = os.getenv("RMQ_PORT", 0)
PACER_RMQ_USERNAME: str = os.getenv("RMQ_USERNAME", "")
PACER_RMQ_PASSWORD: str = (os.getenv("RMQ_PASSWORD", ""))
PACER_RMQ_VIRTUAL_HOST: str = os.getenv("RMQ_VHOST", "/")
PACER_RMQ_PROTOCOL: str = os.getenv("RMQ_PROTOCOL", "amqp")

PACER_INVESTIGATION_OPS_EXCHANGE: str = "investigation-ops-exchange"
PACER_INVESTIGATION_OPS_ROUTING_KEY: str = "investigation.ops"

CELERY_TIMEZONE: str = TIME_ZONE
CELERY_ACCEPT_CONTENT: list = ["application/json"]
CELERY_TASK_TIME_LIMIT: int = 30 * 60
CELERY_BROKER_URL: str = f"{RABBITMQ_BROKER_SETTINGS.get("protocol")}://"
CELERY_BROKER_URL = f"{CELERY_BROKER_URL}{RABBITMQ_BROKER_SETTINGS.get("username")}:{RABBITMQ_BROKER_SETTINGS.get("password")}@" if RABBITMQ_BROKER_SETTINGS.get(
    "username") and RABBITMQ_BROKER_SETTINGS.get("password") else CELERY_BROKER_URL
CELERY_BROKER_URL = f"{CELERY_BROKER_URL}{RABBITMQ_BROKER_SETTINGS.get("host")}:{RABBITMQ_BROKER_SETTINGS.get("port")}" if RABBITMQ_BROKER_SETTINGS.get(
    "port") else f"{CELERY_BROKER_URL}{RABBITMQ_BROKER_SETTINGS.get("host")}"
CELERY_BROKER_URL = f"{CELERY_BROKER_URL}/{RABBITMQ_BROKER_SETTINGS.get("vhost")}" if RABBITMQ_BROKER_SETTINGS.get(
    "vhost") else CELERY_BROKER_URL

SECRET_KEY: str = os.getenv("SECRET_KEY", "8snh6_#tk+l=*n#ni@prha&^_kt13da@&64tk&6l@8gn!fppxv")

# WEBSOCKET CONFIG
WEBSOCKET_DEFAULT_ROOM_NAME = "messages"

WEBSOCKETS_RMQ_HOST: str = quote(os.getenv("WEBSOCKETS_RMQ_HOST", os.getenv("RMQ_HOST", "")))
WEBSOCKETS_RMQ_PORT: int = os.getenv("WEBSOCKETS_RMQ_PORT", os.getenv("RMQ_PORT", 5672))
WEBSOCKETS_RMQ_USER: str = quote(os.getenv("WEBSOCKETS_RMQ_USER", os.getenv("RMQ_USERNAME", "")))
WEBSOCKETS_RMQ_PASS: str = quote(os.getenv("WEBSOCKETS_RMQ_PASS", os.getenv("RMQ_PASSWORD", "")), safe="")
WEBSOCKETS_RMQ_VHOST: str = quote(os.getenv("WEBSOCKETS_RMQ_VHOST", os.getenv("RMQ_VHOST", "/")))
WEBSOCKETS_RMQ_PROTOCOL: str = os.getenv("WEBSOCKETS_RMQ_PROTOCOL", os.getenv("RMQ_PROTOCOL", "amqp"))

WEBSOCKETS_BROKER_URL: str = f"{WEBSOCKETS_RMQ_PROTOCOL}://{WEBSOCKETS_RMQ_USER}:{WEBSOCKETS_RMQ_PASS}@{WEBSOCKETS_RMQ_HOST}:{WEBSOCKETS_RMQ_PORT}/{WEBSOCKETS_RMQ_VHOST}"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_rabbitmq.core.RabbitmqChannelLayer",
        "CONFIG": {
            "host": WEBSOCKETS_BROKER_URL,
            "expiry": 60,
        },
    },
}

USER_MSG_CACHE_TYPE_FILTERS_KEY_SUFFIX: str = "_ui_profile_filters"
USER_MSG_CACHE_QUERY_FILTERS_KEY_SUFFIX: str = "_ui_profile_query_filters"

USER_CACHE_KEYS_SUFFIX: dict = {
    name: value
    for name, value in globals().items()
    if name.startswith("USER_MSG_CACHE_") and isinstance(value, str)
}

ADMIN_ROLE_GROUP_NAME: str = "Administrator"

TESTING_MODE: bool = False
