# Generated by Django 5.2.4 on 2025-07-18 09:15

import psqlextra.backend.migrations.operations.add_default_partition
import psqlextra.backend.migrations.operations.create_partitioned_model
import psqlextra.manager.manager
import psqlextra.models.partitioned
import psqlextra.types
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('object_identifiers', models.JSONField(blank=True, null=True, verbose_name='Object identifiers')),
                ('payload_format', models.CharField(max_length=255, verbose_name='Message format')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('errored', models.BooleanField(default=False, verbose_name='Errored')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
            partitioning_options={
                'method': psqlextra.types.PostgresPartitioningMethod['RANGE'],
                'key': ['created_at'],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        psqlextra.backend.migrations.operations.add_default_partition.PostgresAddDefaultPartition(
            model_name='Message',
            name='default',
        ),
    ]
