# Generated by Django 5.2.4 on 2025-07-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_message_processed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hash',
            field=models.CharField(max_length=255, null=True, verbose_name='Hash'),
        ),
    ]
