# Generated by Django 5.2.4 on 2025-07-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_message_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
