# Generated by Django 5.2.4 on 2025-07-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_message_type_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='unknown', max_length=255, verbose_name='Message type'),
        ),
    ]
