# Generated by Django 5.2.4 on 2025-09-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_message_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation', models.CharField(max_length=255, verbose_name='Investigation')),
                ('has_doi', models.BooleanField(default=False, verbose_name='Has DOI')),
                ('has_panosc_item', models.BooleanField(default=False, verbose_name='Has PaNOSC item')),
                ('first_check_date', models.DateTimeField(auto_now_add=True, verbose_name='First check date')),
                ('last_check_date', models.DateTimeField(auto_now=True, verbose_name='Last check date')),
                ('check_retries', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'InvestigationCheck',
                'verbose_name_plural': 'InvestigationChecks',
            },
        ),
    ]
