# Generated by Django 5.2.4 on 2026-03-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_investigationcheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='processed_at',
        ),
        migrations.AddField(
            model_name='message',
            name='processing_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processing end'),
        ),
        migrations.AddField(
            model_name='message',
            name='processing_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processing start'),
        ),
    ]
