# Generated by Django 5.2.4 on 2026-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_message_processed_at_message_processing_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='processing_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Processing time'),
        ),
    ]
