# Generated by Django 5.2.4 on 2026-03-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_message_processing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Processing time'),
        ),
    ]
