# Generated by Django 5.2.4 on 2026-03-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_message_processing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='acknowledged',
            field=models.BooleanField(default=False, verbose_name='Acknowledged'),
        ),
    ]
