# Generated by Django 5.2.4 on 2026-03-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_message_acknowledged'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='exchange_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Exchange name'),
        ),
        migrations.AddField(
            model_name='message',
            name='routing_key',
            field=models.CharField(max_length=255, null=True, verbose_name='Routing key'),
        ),
    ]
