# Generated by Django 5.2.4 on 2026-03-30 14:33

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_message_exchange_name_message_routing_key'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='dashboard_m_message_3533fb_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['object_identifiers'], name='dashboard_m_object__c17d81_gin'),
        ),
    ]
