# Generated by Django 5.2.4 on 2026-03-30 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0012_message_dashboard_m_message_3533fb_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricted_message_types', models.CharField(blank=True, max_length=255, null=True, verbose_name='Restricted message types')),
                ('allowed_object_identifiers', models.CharField(blank=True, max_length=255, null=True, verbose_name='Allowed object identifiers')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'GroupProfile',
                'verbose_name_plural': 'GroupProfiles',
            },
        ),
    ]
