# Generated by Django 5.2.4 on 2026-03-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_groupprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='restricted_message_types',
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='allowed_message_types',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Allowed message types'),
        ),
    ]
