# Generated by Django 5.2.4 on 2026-03-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_groupprofile_restricted_message_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='msg_actions_allowed',
            field=models.BooleanField(default=False, verbose_name='Message actions allowed'),
        ),
    ]
