# Generated by Django 5.2.4 on 2026-04-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_groupprofile_msg_actions_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationcheck',
            name='visit_id',
            field=models.CharField(default='', max_length=255, verbose_name='Visit ID'),
        ),
    ]
