# Generated by Django 5.2.4 on 2026-06-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_investigationcheck_visit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='allowed_message_types_reingest',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Allowed message types'),
        ),
    ]
