# Generated by Django 5.2.4 on 2026-03-31 12:11
from django.contrib.auth.models import Group
from django.db import migrations

from dashboard.models import GroupProfile


def create_default_groups(_apps, _schema):
    group_names: list = ["Administrator", "Readers", "RestrictedReaders", "BL01", "BL04", "BL06", "BL09", "BL11",
                         "BL13", "BL16", "BL20", "BL22", "BL24", "BL25", "BL29", "BL31"]

    for group_name in group_names:
        _, _ = Group.objects.get_or_create(name=group_name)


    readers = Group.objects.get(name="Readers")
    readers_profile = readers.groupprofile
    readers_profile.allowed_message_types = "proposal-sync,investigation-ops,dataset-ingestion,internal-dataset-ingestion"
    readers_profile.allowed_message_types_reingest = "investigation-ops,dataset-ingestion,internal-dataset-ingestion"
    readers_profile.save()

    restricted_readers = Group.objects.get(name="RestrictedReaders")
    restricted_readers_profile = restricted_readers.groupprofile
    restricted_readers_profile.allowed_message_types = "proposal-sync,investigation-ops,dataset-ingestion,internal-dataset-ingestion"

    restricted_readers_profile.save()

    for bl_group in [i for i in group_names if i.startswith("BL")]:

        group = Group.objects.get(name=bl_group)
        group.groupprofile.allowed_message_types = "proposal-sync,dataset-ingestion,internal-dataset-ingestion"
        group.groupprofile.allowed_object_identifiers = bl_group
        group.groupprofile.save()


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0018_groupprofile_allowed_message_types_reingest'),
    ]

    operations = [
        migrations.RunPython(create_default_groups)
    ]
